### ISSUE TITLE
Missing tool tip in Shiny app  

### ISSUE THREAD

**Issue by ThoDuyNguyen** [timelyportfolio/parsetR#2] opened 2015-10-07 07:49 UTC
When I test my code through RStudio (Viewer or browser), the tool tip is displayed correctly. 
But when using in Shiny application, it looked like the tool tips was missing

``` r
group <- structure(list(location = structure(c(1L, 1L, 1L, 2L, 2L, 3L, 
3L, 4L, 5L, 5L, 6L, 6L, 7L, 8L, 8L, 8L, 9L, 9L, 9L, 10L, 10L, 
11L, 11L, 11L, 11L, 12L, 12L, 13L, 13L, 13L, 13L, 14L, 14L, 15L, 
16L, 16L, 16L, 16L, 17L, 17L, 17L, 18L, 18L, 18L, 18L), .Label = c("ATC", 
"CN-DAINAM", "CN-GIALAI", "CN-LIENDANH", "CN-LONGAN", "CN-NGHEAN", 
"DC-BACGIANG", "DC-BENTRE", "DC-CONGTHANH", "DC-DAINAM", "DC-DATLOC", 
"DC-HAIDUONG", "DC-HUNGYEN", "DC-SSMOI", "DC-THIENNAM", "HN-BRANCH", 
"HP-BRANCH", "SM-THAIBINH"), class = "factor"), level = structure(c(1L, 
2L, 3L, 1L, 2L, 1L, 2L, 6L, 1L, 2L, 1L, 2L, 2L, 1L, 2L, 3L, 1L, 
2L, 3L, 1L, 2L, 1L, 2L, 3L, 4L, 1L, 2L, 1L, 2L, 3L, 4L, 1L, 2L, 
1L, 1L, 2L, 3L, 6L, 1L, 2L, 3L, 3L, 4L, 5L, 6L), .Label = c("1", 
"2", "3", "4", "5", "6"), class = "factor"), amount = c(13L, 
62L, 20L, 29L, 81L, 3L, 10L, 1L, 1L, 2L, 1L, 2L, 1L, 1L, 9L, 
2L, 10L, 3L, 2L, 21L, 27L, 26L, 355L, 7L, 1L, 6L, 11L, 4L, 5L, 
6L, 3L, 8L, 34L, 1L, 44L, 135L, 1L, 2L, 13L, 9L, 2L, 5L, 5L, 
4L, 4L)), class = "data.frame", row.names = c(NA, -45L), .Names = c("location", 
"level", "amount"))

parset(
    group,
    dimensions = c("level","location"),
    value = htmlwidgets::JS("function(d){return d.amount}"), tension=0.5
    width = "80%", height = 400
)
```

For Shiny code in server: 

``` r
    output$parset <- renderParset(
        parset(group, dimensions = c("level", "location"),
               value = htmlwidgets::JS("function(d){return d.amount}"),
               tension = 0.5)
    )
```

**Comment by timelyportfolio** [comment] 2015-10-07 12:53
Can you copy/paste `sessionInfo()` or `devtools::session_info()`?  Works fine on my side.  Also, what browser are you using?  Hard to debug when I can't see what is happening.  Sorry.

**Comment by jkraut** [comment] 2015-10-10 02:35
I observed the same issue when I deployed `renderParset()` in Shiny.  Using Chrome Version 45.0.2454.101 (64-bit)

Example and Session Info Below:

``` r
library(shiny)
library(parsetR)
server <- function(input, output) {
  output$distPlot <-
    renderParset(parset(Titanic))
}

ui <- fluidPage(
    mainPanel(parsetOutput("distPlot"))
)

shinyApp(ui = ui, server = server)
```

``` r
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] parsetR_0.0.1  vcdExtra_0.6-8 gnm_1.0-8      vcd_1.4-1      shiny_0.12.2  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      lattice_0.20-33  zoo_1.7-12       relimp_1.0-4     digest_0.6.8     lmtest_0.9-34    mime_0.4        
 [8] MASS_7.3-43      R6_2.1.1         jsonlite_0.9.17  xtable_1.7-4     qvcalc_0.8-9     rstudioapi_0.3.1 Matrix_1.2-2    
[15] tools_3.2.2      htmlwidgets_0.5  yaml_2.1.13      httpuv_1.3.3     colorspace_1.2-6 htmltools_0.2.6  nnet_7.3-10   
```

**Comment by timelyportfolio** [comment] 2015-10-10 12:04
Would you mind updating to the newest htmlwidgets using devtools::install_github("ramnathv/htmlwidgets")?  There was a tiny bug that caused problems with styling that we fixed in 0.5.1.  Let me know.

**Comment by jkraut** [comment] 2015-10-10 13:35
Still no popup when called through `renderParset()`/`parsetOutput()`

``` r
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] htmlwidgets_0.5.1 parsetR_0.0.1     vcdExtra_0.6-8    gnm_1.0-8         vcd_1.4-1         shiny_0.12.2     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      lattice_0.20-33  zoo_1.7-12       relimp_1.0-4     digest_0.6.8     lmtest_0.9-34    mime_0.4        
 [8] MASS_7.3-43      R6_2.1.1         jsonlite_0.9.17  xtable_1.7-4     qvcalc_0.8-9     rstudioapi_0.3.1 Matrix_1.2-2    
[15] tools_3.2.2      yaml_2.1.13      httpuv_1.3.3     colorspace_1.2-6 htmltools_0.2.6  nnet_7.3-10     
```

**Comment by timelyportfolio** [comment] 2015-10-10 13:38
Ok, thanks.  I will dig deeper when I get back on my computer Monday.

**Comment by jkraut** [comment] 2015-10-10 14:15
Thanks for taking the time to investigate (and in general for making such so many awesome .js integrations)! Just let me know if there is any other info I can provide you for from my end.

**Comment by ThoDuyNguyen** [comment] 2015-10-12 14:48
It seems that @jkraut provided full information for further investigation (I had left my PC for a while). 
Again, thank @timelyportfolio for your effort in htmlwidgets development. 

Kind regards

**Comment by timelyportfolio** [comment] 2015-10-15 12:48
@ThoDuyNguyen and @jkraut, thanks for pointing this out and providing all the helpful reference information.  The invisible tooltip was caused by a css namespace conflict with bootstrap.  Should be fixed in https://github.com/timelyportfolio/parsetR/commit/8cd92d02fb70e6ecc4b6478ef62466d2ea6af3ad.  Let me know.  Thanks again.

**Comment by ThoDuyNguyen** [comment] 2015-10-15 15:31
I will update and re-test then report the result. 
:dancer:

**Comment by jkraut** [comment] 2015-10-16 03:33
@timelyportfolio - fix worked great.  Thanks for pushing the update.  Loving all the work you're doing at http://www.buildingwidgets.com/.  It's inspired me to learn more JavaScript and I plan on trying my hand at writing a widget when I have more time in a few weeks.  htmlwidgets really pushes the limit of what you can do with R

**Comment by ThoDuyNguyen** [comment] 2015-10-16 04:31
@timelyportfolio: the new code fixed bug, tested on both RStudio and Shiny Server.
Thank for the fix

**Comment by timelyportfolio** [comment] 2015-10-16 12:51
Glad to hear @ThoDuyNguyen and @jkraut.  @jkraut let me know if you want to work together on a new `htmlwidget`.  It might speed the learning process.

**Closed as completed by timelyportfolio** 2015-10-16 12:51 UTC

**Comment by jkraut** [comment] 2015-10-20 03:16
@timelyportfolio - Would be awesome to work with you on a new `htmlwidget`.  I don't know much .js yet, but just picked up JavaScript: The Good Parts and plan on reading when I have more time in a few weeks.  Once I've gone through that I'll let you know, as I'd imagine that will make widget building easier
